### ISSUE TITLE
Make benthic attribute colors in site ring charts consistent

### ISSUE THREAD

**Issue by saanobhaai** [data-mermaid/mermaid-dash#129]
"Hard coral", e.g. should be the same color across all sites, no matter how many categories appear at a site. Emily will provide hex codes for all possible benthic categories.

Also, as Emily comments below, categories should be in same order.

**Comment by esdarling** [comment]
![benthic hex colour-donut plot](https://user-images.githubusercontent.com/3466848/66578424-12ad5480-eb49-11e9-9f21-769badc6ff69.png)

**Comment by esdarling** [comment]
Would be great if hard coral could start at top, and then ring builds clockwise, so same chart as above but flipped horizontally
