### ISSUE TITLE
Intro Summary info modal & its control button

### ISSUE THREAD

**Issue by tienhoah** [data-mermaid/mermaid-dash#133]
![Screen Shot 2019-10-09 at 12 27 34 PM](https://user-images.githubusercontent.com/6288799/66513740-9c4d1b80-ea90-11e9-97a1-fdbb793f213c.png)

**Comment by esdarling** [comment]
New language for 'disclaimer' window modal: 

Welcome to the MERMAID dashboard. This information represents the time, resources and expertise of hundreds of coral reef scientists around the world.

1. If you would like to publish any analyses based on these data, please contact the appropriate project administrators using the [Contact Admins] button available for each site

(where [Contact Admins] is just the button image, in line)

2) Do not assume data is representative. Some projects have survey sites in geographies to address specific questions (e.g., land-based impacts of reefs, recovery rates from cyclone impacts). Summary data may not reflect overall national statistics. 

Click anywhere to agree to these terms and continue.
