### ISSUE TITLE
[BUG] Layout is too large in height

### ISSUE THREAD

**Issue by brianbancroft** [data-mermaid/mermaid-dash#14]
https://www.loom.com/share/63c7e5988ea443dbb340d4aa6bdcc14d

The current height of the app is 100vh + the height of the headerbar. 

This is bad. It should be 100vh all-in, at most. 

This can be fixed by setting the height of the map top `height: calc(100vh - <headerbarHeight>);`

**Comment by tienhoah** [comment]
https://github.com/data-mermaid/mermaid-dash/pull/19

**Comment by brianbancroft** [comment]
Closed by #19
