### ISSUE TITLE
Use only one Request

### ISSUE THREAD

**Issue by brianbancroft** [data-mermaid/mermaid-dash#15]
At this time, there is no difference between the output of `sites` and `site`, for a given site.

At this time we're seeing API calls in the following components:
- Dashboard
- MapCanvas
- MetricCards
- SideDetail
- SiteList

We should focus on having just one API call, and making this the source of truth. Do it in the App component, for now.

**Comment by tienhoah** [comment]
https://github.com/data-mermaid/mermaid-dash/pull/21

**Comment by tienhoah** [comment]
closes #15
