### ISSUE TITLE
remove map tile seams

### ISSUE THREAD

**Issue by saanobhaai** [data-mermaid/mermaid-dash#176]
Coming back to this; just need to get the thin white seams between tiles out of the map:

![image](https://user-images.githubusercontent.com/5067153/79227372-c7dd0400-7e2d-11ea-8e0d-90dd679205bb.png)

**Comment by gridcell** [comment]
See: https://github.com/SpeciesConservationLandscapes/scl-top/blob/develop/src/lib/leaflet-tilelayer-subpixel-fix.js
