### ISSUE TITLE
zoom to Fiji

### ISSUE THREAD

**Issue by saanobhaai** [data-mermaid/mermaid-dash#181]
Currently, zooming to a set of sites that straddle the international dateline produces suboptimal UX, e.g.
https://dev-dashboard.datamermaid.org/?tag_id=ea5acbd8-85e4-4982-8f29-8559aafcfce1
Zooming to sites yields the whole world, and when you manually zoom, not all sites show up. We should find some way of intuitively showing sites the straddle the line. Maybe this is part of a mapbox refactor?

**Comment by gridcell** [comment]
@tienhoah if we wrap that marker lat/lng (https://github.com/data-mermaid/mermaid-dash/blob/dev/src/components/LeafletMap.js#L530) with Utils.wrapNum, to normalize the coords between -180/180
