### ISSUE TITLE
improve filtered urls

### ISSUE THREAD

**Issue by saanobhaai** [data-mermaid/mermaid-dash#182]
When filtering by country_name, the url reflects a human-readable string, e.g. `Indonesia`. But when filtering by project or organization, the url uses ids, which makes sense in terms of filtering logic but isn't as user-friendly. Thinking we should either
1. Generate slugs on the server, send them through to the client, and have the client use them in the url, which the server then knows how to filter on, or
2. implement a url shortener (maybe something client-side like https://www.freecodecamp.org/news/building-a-simple-url-shortener-with-just-html-and-javascript-6ea1ecda308c/) that is triggered via a `Share`/`copy url` button/workflow

### Update 2020-06-19

- [x] Rename query parameters:

* country_name -> country
* tag_id -> organization
* project_id -> project
* date_min_after/date_max_before -> date
    + comma delimit start date and end date

- [x] Use project names instead of project ids
- [x] Use tag names instead of ids

Project and tag names can be mapped to id's to make API calls

**Comment by gridcell** [comment]
![mermaid_dashboard_urls](https://user-images.githubusercontent.com/915189/84927687-09826900-b082-11ea-8211-e4c4a0c00342.png)
