### ISSUE TITLE
Metric card component

### ISSUE THREAD

**Issue by gridcell** [data-mermaid/mermaid-dash#3]
Metric component store large number with the metric name under number (see example below).

Metric numbers should display between 0 - 999 and after that

1K (1000 to 999,999)
1M (1,000,000 to 999,999)
etc.

where the title holds the actual number

Mockup:

![metric_card](https://user-images.githubusercontent.com/915189/59061711-f3c84a00-8858-11e9-8ff0-184ab371bc87.png)

**Comment by tienhoah** [comment]
https://github.com/data-mermaid/mermaid-dash/pull/11

**Comment by brianbancroft** [comment]
Closed by #11
