### ISSUE TITLE
Bar chart component

### ISSUE THREAD

**Issue by gridcell** [data-mermaid/mermaid-dash#4]
Required

- Parameter: 2d array of values
- Parameter: X/Y labels
- Mouse hover shows bar value

Optional Parameters:

- set colors

![barchart](https://user-images.githubusercontent.com/915189/59062535-ee6bff00-885a-11e9-9d1e-e3e75eda1180.png)

**Comment by tienhoah** [comment]
https://github.com/data-mermaid/mermaid-dash/pull/12

**Comment by brianbancroft** [comment]
Closed by #12
