### ISSUE TITLE
Clicking a cluster icon zooms in to close

### ISSUE THREAD

**Issue by gridcell** [data-mermaid/mermaid-dash#53]
Clicking a cluster icon zooms in to close.  Also, the user shouldn't be able to zoom in more than the maximum zoom level of the base layer

<img width="1343" alt="Screen Shot 2019-08-08 at 10 20 57 AM" src="https://user-images.githubusercontent.com/915189/62723886-92db0080-b9c6-11e9-9faf-0912bfa37616.png">

**Comment by tienhoah** [comment]
I have talked about this issue with Brian that area of map tiles (may be more but haven't found yet) are broken, the map works fine on  similar zoom every where else. We tested and decided that max zoom 17 is good overall. 
site note: we may not stick with this map layer in the future, so see what can be changed after that
