### ISSUE TITLE
Add bleaching site metric cards

### ISSUE THREAD

**Issue by saanobhaai** [data-mermaid/mermaid-dash#77]
At https://summary-api-dev.datamermaid.org/v1/sites/ is an example of new site-level averages for the two bleaching sample units, `colonies_bleached` and `quadrat_benthic_percent`. We need a card for each to display these -- for which we'll need specification.

**Comment by esdarling** [comment]
![IMG_5997](https://user-images.githubusercontent.com/3466848/64129503-67abbd00-cd8a-11e9-8cf1-527f0ab1916d.JPG)
Sample bleaching mockup

**Comment by esdarling** [comment]
![IMG_6207](https://user-images.githubusercontent.com/3466848/66209696-f1022800-e685-11e9-960d-f91906a62ff4.JPG)

**Comment by saanobhaai** [comment]
Nick we should use the same colors for this ring as for the other benthic metrics -- see 129. #129

**Comment by saanobhaai** [comment]
@tienhoah We'd like to make the ring total = 100%, and then have the %s from the api represented as fractions of that 100%, not as fractions of the total of the reported %s. So if % hard coral = 33, then the hard coral color on the ring would take up 1/3 of the ring.

Then, for any difference (i.e. 100% - total bleaching %s) we should fill in with a light white/grey and label "other".

**Comment by gridcell** [comment]
merged
