### ISSUE TITLE
% coral cover histogram redesign

### ISSUE THREAD

**Issue by saanobhaai** [data-mermaid/mermaid-dash#99]
1. Redesign (ideally produce mockups)
2. Implement, either by modifying existing widget or making a new one

Main goal is to add some kind of lines showing 10% and 30% thresholds. We should then create an (info) icon of some kind, perhaps in lower right of card, that users can click for information on what these %s and thresholds mean (perhaps in a modal).

Should also consider how to show how many sites are doing well/medium/poorly. Here's one example from a recent report:
![image](https://user-images.githubusercontent.com/5067153/84188935-68ccf180-aa62-11ea-8835-b84d6a9009a6.png)
This shows individual sites ("lollipop chart"); how sites are doing is shown via color and via proportion of yaxis. This is great but I'm not sure would scale; for the app we could have 0 sites, 1 site, or many thousands of sites. Perhaps we could do something like this or the histogram, with dynamic bins to show as many as possible? I also wonder about reversing the axes.

Other ideas also welcome -- without spending a huge amount of time, would be good to iterate on a few ideas before implementing.

**Comment by saanobhaai** [comment]
A few items for discussion:

- gist to create 2D matrix from summary api saved json for all sites: https://gist.github.com/saanobhaai/b75967a0c9837d998e8ea19476a4b1b8
- result with some logic embedded in cell formulae to produce data for charts: 
[hard_coral.xlsx](https://github.com/data-mermaid/mermaid-dash/files/4806378/hard_coral.xlsx)
- simple histogram; basically same as what Dustin did: https://plotly.com/~squarewater/4/
- 2D contours: https://plotly.com/~squarewater/5/
Much as I want it to, I don't think this will work.

Also experimented with lollipop chart aggregation but couldn't make it work.

**Comment by saanobhaai** [comment]
Hi @tienhoah -- did some experimentation and discussed with Dustin, and think this boils down to the enhancements represented by https://plotly.com/~squarewater/4/ (but not quite those colors):

- color 0-10, 10-30, and 30+ bins with d7191c, ffffbf, and 2c7bb6 respectively (from https://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=5 -- feel free to adjust for similar red/orange/blue colors that are colorblind-safe)
- add threshold lines
- add "more info" button
- add modal like "About" launched from "more info" that explains the chart, particularly the threshold lines (to come from Emily)

**Comment by esdarling** [comment]
For the "More info" model, here's some text that would work about the thresholds, and a link to a doc with more details. 

**

Live coral cover maintains coral reef growth through carbonate production. Studies have shown that a minimum of >10% hard coral cover is required for net-positive carbonate production. A precautionary threshold to maintain biodiversity, structural complexity and fisheries production is ~30% live coral cover. Analyses are currently underway to test and validate these thresholds. The coral cover indicator (and other indicators supported by MERMAID) support a Recommendation from the International Coral Reef Initiative for the inclusion of coral reefs and measurable indicators within the CBD Post-2020 Global Biodiversity Framework (https://www.icriforum.org/post2020/). Measuring the national status and trends of live coral cover and other key indicators will support conservation and management interventions to mitigate threats and maintain reefs above critical functioning thresholds. 

References 

https://www.icriforum.org/post2020/

WCS Policy Brief on Coral Reef Indicators (https://c532f75abb9c1c021b8c-e46e473f8aadb72cf2a8ea564b4e6a76.ssl.cf5.rackcdn.com/2019/10/28/932fl66562_Post_2020_Coral_Target_2p_v7.pdf)

Darling et al. “Social–environmental drivers inform strategic management of coral reefs in the Anthropocene.” Nature Ecology & Evolution, 2019.

McClanahan et al. “Critical thresholds and tangible targets for ecosystem-based management of coral reef fisheries.” PNAS, 2011.

McClanahan et al. “Global baselines and benchmarks for fish biomass: comparing remote reefs and fisheries closures.” MEPS, 2019

Perry et al. "Caribbean-wide decline in carbonate production threatens coral reef growth". Nature Communications, 2013. 

Perry et al. "Loss of coral reef growth capacity to track future increases in sea level". Nature, 2018.
